/* eslint-disable max-len */
const CarData = [
  {
    name: [
      'Honda Civic VII sedan, 2004, 1,6 VTEC',
      'FORD FOCUS 1.6 TDCI 2014 r Krajowy Serwisowany  polecam. Zamiana',
      'Audi a3 TFSI  2.0 Quattro 200 koni 60 tyś Bez wkładu finansowego!',
      'Renault Thalia 1.4 Benzyna-Gaz',
      'Sprzedam Peugeot 307 1.6 ben+gaz 2001r',
      'Ford Grand C-MAX 1.5 EcoBoost 150KM Automatic 5osobowy Titanium I Wł Serwis ASO Ford',
      'Volkswagen Passat 1.9 TDI Kombi',
      'Volvo s60 2.4 benzyna Sprowadzony',
      'Kia Ceed Klima Od Pierwszego Wł Dwa Komplety Kół Serwisowany Sprowadzony',
      'Oddam cesje, Skoda superb, 2.0 benzyna, 220 koni',
      'Hyundai ix20',
      'skoda fabia 1.4 fsi',
      'Kia sportage 2.0 crdi 4x4 zarejestrowany Anglik',
      'Opel Astra Opel Astra1.7cdti 2014 rok ! Polift !',
      'BNW Seri 1 1.4 D Klimatyzacja M Pakiet Wewnętrzny Bardzo Oszczędny',
      'Audi A6 Allroad',
      'Ferrari 360 1/378',
      'BMW Seria 7 BMW F02 750Li',
      'Skoda Octavia III Style 1,5 TSI 150km',
      'Citroen c2 1.6 vtr',
      'Volvo XC 60 PEREŁKA 50705 KM 1WŁ. Blis 4*4 Kamery 360 Full Led Acc Keyless',
      'Nissan Almera N16',
      'Golf 4 IV 1.9tdi Anglik',
      'Audi A4 B8 S-LINE QUATTRO 2.0 TFSI 2016 r.',
      'Opel Agila KLIMATYZACJA 1,2 benzyna 86KM',
      'Toyota Auris Toyota auris lift hybryda automat',
      'PEUGEOT 5008 5-OSOBOWY 2,0 HDI 150KM 2011r.',
      'RenauLt Clio 1.4/98KM*2007 KLimaTroNiC*3-DrzWi*OpłaTy 2023*',
      'BMW E46 330d Automat',
      'Mercedes-Benz Klasa E Mercedes W210 2,7 CDI',
      'Alfa Romeo Giulia Alfa Romeo Giulia SALON PL',
      'BMW E46 compact 1.8',
      'Audi q7 4l 2008r',
      'Audi Q7 AUDI Q7 hybryda 2021 r. 55 TFSI e IDEALNY STAN Niski przebieg',
      'Mitsubishi outlander 2.0 DID',
      'Audi A4 B6 1.9 TDI AVF Avant',
      'Audi Q3 Od ręki - 1.4 TFSIe (245KM) | + Pakiet Technology + Sun & Light',
      'Nissan Juke Nissan Juke 1.6B, Skóra, Kamera, Automat. Gorąco POLECAM!',
      'Audi A4 Audi 97',
      'Hyundai Tucson 2,0i 141KM_114tys.km_ Z Niemiec Zarejestrowany w PL_SKÓRA _KLIMATRONIK',
      'C3*Picasso*Super stan*Bez 2masy i fapa*145tys km',
      'Audi A6 Avant 2.0 TDI 190 KM, S LINE, Oryginał Lakier i Przebieg',
      'Sprzedam Audi a3 1,9 TDI',
      'Audio A4 Allroad 2.0 Quattro',
      'Citroën C4 Grand Picasso panoramadach,navi,xenon 7 osobowy',
      'Nissan Qashqai Pierwszy właściciel,gwatancja producenta do 08.08.2023',
      'Volvo XC 90 Volvo XC 90 2.4 185 KM',
      'Audi A6 C5 1.9 TDI 110KM',
      'Suzuki Sx4 S-cross. salon PL , bezwypadkowe , garażowany Serwis ASO',
      'Jeep Compass',
      'Dacia Sandero 1.5 Dci 90KM*5L -100km*2010* Klima*SUV*Hak* GWARANCJA',
      'Seat Alhambra 7foteli 2004 1.9 130KM',
      'Fiat Ducato Kamper',
      'Opel Astra 1.4 Turbo 150KM-automat-salon PL-mały przebieg-lub zamiana',
      'KIA PICANTO Klimatyzacja, Podgrzewane Fotele',
      'BMW Seria 3 2.0 benz 129KM 109.000km udokumentowany',
      'BMW Seria 7',
      'Renault Captur Renualt Captur',
      'Mazda 5 2.0 D 143KM 6b Manual 2007, 7 osobowa',
      'Opel Zafira 138000 km,bezypadkowy,7 osob,zamiana,raty!!!',
      'Audi A6 Allroad quattro 55 TDI tiptronic quatrro 344 KM DOSTĘPNE OD RĘKI B&O LED',
      'Dwa samochody w cenie jednego',
      'Peugeot 407sw 2.0HDI 2006r',
      'Ford KA Ford Ka doinwestowany',
      'Seat Ibiza 1.2 Benzyna 60 KM 3-Drzwi Kamera Cofania DVD Zadbana Bez Rdzy',
      'Ford Grand C-MAX Duża Nawigacja Klima Powershift Bogate Wyposażenie pełna Faktura 23%',
      'Zafira 1,9 CDTI 120km 2007r',
      'Mercedes-Benz CLA Shooting Brake AMG 306KM MultiBeam Burmester Panorama Hak FV23%',
      'Mitsubishi Outlander',
      'Peugeot 208 Active Pack 1.2 BEMNZYNA 75KM 2022 !! OD RĘKI !!',
      'Volvo XC 60 Bogate wyposażenie Salon Pl',
      'Opel Vectra Bogate Wyposażenie Nawigacja POLIFT',
      'Vw Touran  2.0 tdi 8v 140 KM',
      'Renault Kadjar Bogate wyposażenie, super stan!!!',
      'Ford Transit Courier Ford Transit Courier',
      'BMW X5 M - Pakiet Dostępna od ręki. Również inne kolory oraz wersje',
      'Seat Altea 2009 R Alu Klima Serwis Niski Przebieg',
      'Skoda RAPID 2016 rok; 1,6 TDI 116KM, bogato wyposażony, zadbany, stan bardzo dobry',
      'Peugeot 508 kombi sw',
      'Ford Kuga 2.0 TDCI !! Nawigacja !! Kamera cofania !! Pół skóra !!',
      'Volvo v60 2011rok',
      'Volvo S60 s60',
      'Sprzedam zadbana audi sline X2  Quatro',
      'Sprzedam Opel Vectra C',
      'BMW Seria 3 F31 316d oryginał Bezwypadek! okazja!',
      'Honda Accord Honda Accord VIII 2.4 Executive',
      'Seat Leon – rocznik 2010',
      'Citroen berlingo II 1.6 HDI uszkodzony',
      'BMW X6 E71 3.0 Diesel 286KM',
      'Mercedes-Benz Klasa E LIFT E350 3.5 V6 306HP Skóry Panorama Navi GWARANCJA',
      'Nissan Patrol GR 3.0 TDI, 2000r.',
      'Ford Fiesta 2004r. 1.3 benz',
      'Mercedes-Benz GLA 1 właściciel,super stan,manual',
      'BMW 320d 2,0 Diesel 177ps 12/2009 r zadbana i sprawna',
      'Toyota Yaris 204 Toyota Yaris 1.0 Premium + CITY, salon Polska',
      'Jaguar XF XII.2019 Full Led Duża Navi 10,2’’ Kamera Carplay Fotele Elek.+Ogrz.',
      'Opel Astra 1.6 benzyna 115KM klima Zapraszam',
      'Renault Laguna',
      'Hyundai Genesis GENESIS 3,8 325KM nówka-zarejestrowany w Polsce',
      'Peugeot 407 coupe 2.7 v6',
      'Audi A4 Audi a4 2.0 tdi',
      'Peugeot  5008 1.6 hdi Automat',
      'Volkswagen Multivan Cesja leasingu, raty stałe, samochód na gwarancji',
      'Mitsubishi ASX ZAREJESTROWANY !!! Benzynka / Super !!! z Niemiec / GWARANCJA !!!',
      'Peugeot 3008 Allure Pack 1.2 PureTech 130KM 2WD EAT8',
      'Ford Mondeo 1.6 mpi zamiana',
      'Audi Q7 Audi Q7 3.0 TDI Quattro 4x4 Tiptronic - S Line',
      'Volkswagen Multivan Cesja leasingu, raty stałe, samochód na gwarancji',
      'Mitsubishi ASX ZAREJESTROWANY !!! Benzynka / Super !!! z Niemiec / GWARANCJA !!!',
      'Toyota RAV4 Pierwszy właściciel-super stan',
      'Fiat Tipo OKAZJA , Mega wersja, BEZWYPADKOWY , skóry, radar , AUTOMAT TANIO',
      'Ford Fiesta 1.3 benzyna, klima, podgrzewana szyba, niski przebieg 97 tys km!',
      'Audi A3 8P 2008 rok',
      'Volvo C30, 1.6 Benzyna, 2007 rok, tempomat, podgrzewane fotele',
      'Peugeot 208 GT line 1.2 turbo benzyna ***LED full***',
      'Peugeot 206 Piękny Peugeot 206 1.4 benzyna z klimatyzacją 5drzwi',
      'Dacia Logan DACIA LOGAN MCV II LPG, pierwszy właściciel, kupiona w polskim salonie',
      'Ford Ka 1.3 Benzyna// Klimatyzacja // Miejski//Zamiana',
      'Toyota Corolla 2000r 1.4 benzyna',
      'Peugeot 207 Peugeot 207 sport 156km!!! skora panorama',
      'BMW Seria 3 BMW 318i e90 LPG piątej generacji Prince Vialle',
      'Dodge Grand Caravan Dodge Caravan Niski przebieg LPG Super stan',
      'Renault Clio 1,2 100KM, Klimatyzacja, Bezwypadkowy, Idealny Stan, Opłacony',
      'Dacia Logan 1,2i ABS, ESP, el. szyby, 73KM, 50tys.km, 2016r.',
      'Sprzedam Audi A4 B8 s-line',
      'Renault Megane Renault Megane 1.4 130 KM stan BD.',
      'Ford Probe Ford Probe 2.5 V6 mały przebieg !!!',
      'Renault Laguna 2.0 T. B. 170KM-165tysięcy- BI-Xenon Panoramy TRZEPOWO',
      'BMW Seria 1 Advantage 150 KM Aut. Salon PL Serwis ASO gwarancja 12 msc Navi FV23%',
      'Meriva 1.4 88kw rok 2011 tylko 96 tyś jeden właściciel w Polsce',
      'Mercedes Benz ML 320 CDI Bez Airmatic Dynamic Xenon Alkantara Navi',
      'Volkswagen Multivan HIGHLINE',
      'Suzuki Swift 1.3 Benzyna/Klima',
      'Opel Frontera 2.2 DTI long 2000 4x4 diesel',
      'A8 3.0 TDI Webasto',
      'Audi A4 35 TFSI sedan automat cesja najmu',
      'Volvo V70 1,6D Klima, alu, NAVI, skóra, 2010r.',
      '2009 Ford Mustang GT 4.6 Premium',
      'Porsche Cayenne S śliczny ,ZAMIANA stan bdb zarejestrowany w PL',
      'Volkswagen Golf Plus 1.9TDI-105KM-Climatronic-Alus16-GFotele-192Tys-NoweOplaty-TechnicznTOP',
      'Citroen C5 x7 2009',
      'Dodge Caliber bardzo ladny .sprowadzony oplacony',
      'Mercedes ML 350 CDI BLUETEC 4-Matic',
      'Toyota Avensis zadbana, jak nowa zakupiona w Polskim salonie Toyoty',
      'Sprzedam Jeep Grand Cherokee 5.7hemi, gaz, skrzynią po remontie',
      'Passat serwisowany 2015, B8, Highline, 2.0 TDI, 180.000 km, 190 KM',
      'BMW X1 BMW Xdrive28i Sport 245KM 2017r',
      'Hyundai Tucson 1.6 GDI',
      'BMW Seria 1 Bmw seria 1 diesel',
      'TOYOTA AYGO 1.0B LIFT model 2011 super stan bezwypadkowa  serwisowana',
      'Ford Kuga Sprzedam Zamienię po opłatach zarejstrowany',
      'Volkswagen Golf',
      'MINI ONE ** Super Stan Alu ** Sprowadzony **',
      'Skoda Octavia Skoda Octavia',
      'Volvo S60 Okazyjna Cena Rezerwacja',
      'Volkswagen Polo 1,4TDI Klima, alu, el. szyby x4, 188tys.km, serwis, 100%, bdb, 2009r.',
      'Skoda Roomster Niski Przebieg, Z Niemiec, Opłacona, Zadbana',
      'Suzuki Jimny JIMNY PRO, 1.5 DOHC 102KM, N1, 4WD, Zadzwoń! Sprawdź! Off Road, 2022',
      'Audi A4 Audi A4 Sline 3.0 Quatro',
      'MINI ONE ** Super Stan Alu ** Sprowadzony **',
      'Skoda Octavia Skoda Octavia',
      'Volvo S60 Okazyjna Cena Rezerwacja',
      'Volkswagen Polo 1,4TDI Klima, alu, el. szyby x4, 188tys.km, serwis, 100%, bdb, 2009r.',
      'Renault Scenic 1,5DCI Klima, alu, 7 osób, 2009r.',
      'Renault Kangoo 1,5DCI Klima, 5 osób, el. szyby, lust., XII.2008r.',
      'BMW X6',
      '2018 Dodge Durango R/T 5.7 HEMI V8',
      '2015 Dodge Durango R/T 5.7 HEMI 4x4',
      'Renault Laguna coupe 173 KM',
      'BMW M5 BMW M5 COMPETITION, hamulce karbonowo-ceramiczne, salon PL, MDP',
      'Mercedes W211 e500 4matic 5.0 cena ten weekend',
      'BMW Seria 1 BMW 116ED Seria 1',
      'Nissan Rogue 2,5 LPG Skóra. klima, szyber. po stłuczce drogowej',
      'Sprzedam samochód Opel Insignia',
      'Toyota Verso 1.8 Sol Salon Toyota',
      'Ford Escape 2018 EcoBoost 4X4 automat SEL',
      'Dacia Logan 1.5dci kombi 7 miejsc 2007r sprawny zadbany',
      'SPRZEDAM Seat Altea FR 170 km',
      'golf cabrio 2.0 benzyna',
      'Citroen C5 Exclusive 2,2 Diesel',
      'Audi A4 B7 1.8 Turbo',
      'Seat Ibiza Seat Ibiza Kombi',
      'Volkswagen New Beetle Pierwszy własciciel w Polsce, nowa klimatyzacja, bardzo ładny, zadbany',
      'Isuzu D-Max Pierwszy właściciel, oryginalny przebieg, bezwypadkowy, Isuzu D-Max',
      'BMW Seria1 F20 116i',
      'Ford Fiesta Stan idealny. Zapraszam.',
      'Opel Insignia Opel Insignia 2.0 T Turbo*4x4*SPORT*TOURER*',
      'Citroen Xsara Kombi 2.0HDI 2004r',
      'Ford Ranger Wildtrak',
      'Peugeot 308 Peugeot 308 2008r. Uszkodzony',
      'Mitsubishi L200 Zabudowa kamperowa sama lub z pojazdem',
      'BMW Seria 3 PL,VAT23%,320d xDrive Sport Line, 1rej29/01/2020,2,0l190KM,automat',
      'BMW Seria 3 318 xd x drive 4x4 100% bezwypadkowy piekna',
      'Micra k11 klima el szyby hak',
      'Audi A4 B5 1.9 TDI 110KM 1997',
      'Skoda fabia 1 Kombi',
      'Mercedes-Benz GLE Mercedes-Benz Coupe 350 d 4-Matic',
      'TOYOTA AYGO ! Idealny Stan ! 1.0 benzyna ! 63 tyś przebiegu !',
      'Fiat 500 foat 500 hybryda niski przebieg malo uszkodzony',
      'Sprzedam Peugeot 407',
      'Ford Focus kombi',
      '2018 Dodge Durango GT 3.6 V6',
      'Audi A4 2.0TDI-143KM-BLACK-Clima-Tempo-2PDC-GFotel-CzZmierz-Alu16-NAVI-KiMulti',
      'Mercedes-Benz Klasa C 1.8 CGI 184 KM Salon Polska Pakiet AMG Serwis Stan',
      'Alfa Romeo Giulietta 1,4 B Super Stan',
      'Opel Astra Astra H GTC 1.6 105KM Klimatyzacja Sprowadzona Opłacona',
      'Volkswagen Golf 5 1.6MPI',
      'Volvo XC 70 T6 Polestar w nienagannym stanie',
      'Sprzedam skoda octavia 2008-pierwszy właściciel -salon-ASO',
      'FORD CMAX 2,0 tdci Titanium Sprowadzony // Zarejestrowany',
      'Vw Sharan 1.8T 150Km/LIFT/Automat/HIGHLINE/Xenon/Alu/PIĘKNY',
      'Toyota Aygo jak nowa okazja',
      'BMW 1 - E87 - 2009 r. - 2.0 - KLIMA - 5 DRZWI - 116i',
      'Audi Avant A4B7 Sline',
      'Land Rover Freelander 2004',
      'Renault Megane 1,6 16V/klimatronik/krajowy/elektryka',
      'Opel Astra H 1.7 CDTI',
      'Toyota Auris Bez wypadkowy Niski Przebieg Stan Idealny',
      'Opel Vectra C 2.2 GTS',
      'Skoda Roomster 1,4 MPI, Nowy Rozrząd, Zadbany, Opłacony, Bezwypadkowy',
      'Audi A4 benzyna - zadbany - 1.6 - klimatronik',
      'Ford Focus 2.0 145KM LPG klima alu elektryka gwar. 12 mies.! Warszawa',
      'Opel Insignia 2,0 CDTI atrakcyjny wygląd bogate wyposażenie ZAMIANA',
      'Opel Frontera Long 3.2 benzyna',
      'Seat Leon Piękny Seat Leon 1.8 benzyna w super wersji i stanie',
      'MINI Cooper Mini Cooper 1.6 Klimatyzacja',
      'Jeep Compass JEEP COMPASS 2.4 2020 4X4',
      'Peugeot Partner Long',
      'Ford Mondeo Ford Mondeo Mk4',
      'Honda Civic 1.8 VTEC Automat',
      'Renault Megane Full Led Full Wyp…1.6 130ps',
      'Toyota Yaris Selection Platinum',
      'Opel Corsa C 1.0 Benzyna 2006 rok Wspomaganie',
      'Volvo C30 jeden właściciel / serwisowany / ORYGINAŁ',
      'Opel Signum Klima Alu 16 Xenon Led Parcktronick Tempomat Grzane Fotele',
      'Skoda Karoq Ambition 1.6 TDI 115KM',
      'BMW X7 3.0 xDrive40d (340KM) M Sport | Pakiet M Pro + Pakiet Comfort',
      'Kia Sportage Navi Kamera Xenon',
      'Volkswagen Polo Bezwypadkowy navi zadbany sprowadzony',
      'Audi A6 C5 2.4 V6*LPG*tempomat*szyber*alu*',
      'Ford Fiesta MK6 1.25 z Niemiec po opłatach 5-drzwi',
      'BMW Seria 5 E60_530i_3.0i_272PS_Lift_Benzyna_2007_Full_Piękna_Opłacona_Z Niemiec',
      'Opel vivaro  1.6 140km  bdb stan',
      'Zadbane Audi A3 8P',
      'Sprzedam ford fiesta 2007r 1.3benzynka',
      'Fiat Sedici 2008 napęd automatyczny 4x4 - najlepszy kompan',
      'Fiat Freemont Fiat FREEMONT 7-osobowy',
      'Audi A8 55 TFSI Quattro Tiptronic + ekspertyza serwisowa',
      'Bmw serii 3 e46 320d',
      'Kia Sportage 2.0 Benzyna Idealny Stan z Niemiec',
      'BMW X5 M BMW X5 M M50d',
      'Renault Scenic 1,5dci 2004r.',
      'Fiat Bravo Uszkodzony',
      'Sprzedam Audi A 3',
      'Opel Astra Auto z Gwarancją',
      'Chevrolet Captiva Super Stan Techniczny i wizualny ! KSIAZKA SERWISOWA !Oplacony ! 7 os',
      'Audi A4 B5 2,4 V6 165 KM  LPG',
      '3x S- LINE Audi a4 b8',
      'Almera 1,5 dci klimatyzacja sprawna czeskie dokumenty',
      'ford focus mk2 1.6',
      'Peugeot 307SW 1.6hdi po lifcie',
      'Audi A4 A4 ALLROAD 2.0TFSI 252KM 4x4 quattro / full opcja',
      'BMW Seria 7 BMW 740xd salon Polska !',
      'Volvo V50 2,4Benzyna 170KM Pełna Opcja Skóry Xenon Navi Szyberdach',
      'Citroën C4 SpaceTourer Citroën C4 Grand Picasso SpaceTourer',
      'Audi A6 Audi A6 C6 3.2 V6 Quattro tiptronic 130k przebiegu',
      'Audi A3 8P Sportback 1.9 TDI 105KM Panorama',
      'VW T3 ogórek osobowy caravelle transporter',
      'Volkswagen Tiguan Bogate wyposażenie! Idealny stan! El. Hak!',
      'Fiat Sedici Fiat Sedici z Niemiec opłacony 150 tyś.km',
      'Opel Astra Piękny Opel Astra 1.9 po lifcie w super stanie i wersji',
      'Peugeot 3008 1,6 Hybrid 225KM/ Allure Pack/ Demo dealera/ Dostępny od ręki',
      'Audi A3 2.0TFSI Sportback',
      'Ford Mondeo 1.8 16V Benzyna GHIA Sprowadzony Bezwypadkowy',
      'Śliczny COLT 1.1 *75 KM *5 DRZWI *tylko 183.000km *ZERO RDZY *Top Stan',
      'Hyundai Getz 2008r 1wl tylko 91000km!Okazja!Zarejestrowany Ubezpieczon',
      'Audi a6 c6 3.0 tdi quattro',
      'Grand Scenik 2008  1,9d automat',
      'Mersedes Ml270 Dizel',
      'BMW Seria 3 BMW F31 320d 190 KM M Pakiet',
      'Peugeot 206 CC kabriolet',
      'Merce3.0cdi zamiana',
      'Volkswagen Touareg Vw Touareg',
      'Audi Q5 2014 3.0 TDI 258PS S line WEBASTO !',
      'Mercedes-Benz GLE Amg Salon Pl VAT 23%Bezwypadek',
      'Volkswagen Golf 1.6, Salon Polska, Alarm',
      'Nissan Qashqai 4x4 2,0i 141KM 185.000km ŁADNY Zarejestrowany Solardach',
      'Opel Antara 2.0 CDTI_Automat_2008r_Niemiec!!_Mega Zadbany!!4x4 Polecam',
      'Vw Caddy Stan Bardzo Bardzo dobry! 1,4 mpi Zarejestrowany rok w Polsce',
      'Volkswagen Passat Volkswagen Passat Kombi 1.5 TSI EVO Business DSG',
      'Mercedes-Benz Klasa C Mercedes Klasa C180 Kompressor',
      'Mercedes-Benz Klasa G G63 AMG Pakiet / Felgi 22” / ORYGINALNY MAT',
      'Peugeot 3008 Exclusive 2.0Hdi 163Ps Progi Chromy Navi Panorama Automat Oryginał Lak',
      'Toyota Aygo',
      'Peugeot Expert 2.0, 9cio osobowy zadbany, 6cio biegowa skrzynia',
      'BMW Seria 5',
      'BMW Seria 3 BMW e91 330xi LPG Szwajacaria',
      'Peugeot 2008 Peugeot 2008',
      'Audi RS Q3 2.5 TFSI 400 KM Dostępny OD RĘKI',
      'BMW 640D DRIVE M Packet Sport Diesiel',
      'Jeep Grand Cherokee 3.0, V6, 250KM, Automat, 4X4, Panorama, Overland',
      'Karawan Pogrzebowy VITO 113CDI 2014r',
      'Fiat Seicento 900',
      'Nissan Qashqai 1.3 DIG-T N-Tec | Vat-marża | SalonPolska',
      'Skoda Octavia 1.6 TDI Style',
      'Bmw f10 523i 2010r 140tys przebiegu',
      'Audi A6 c5 2.4Bp',
      'Volkswagen Golf V',
      'Sprzedam Nissana Pixo',
      'Kia Ceed * Klimatyzacja * Zamiana *',
      'Opel Insignia 1.5 Turbo Automat 165 KM 100% oryginalny i bezwypadkowy',
      'Audi A3',
      'Opel Insignia * 2009 * 2.0 * Diesel * 130KM',
      'BMW Seria 3 325i _ Bixenon _ Tempomat _ Szwajcar_',
      'Opel Astra H # 2006 # 1.6 Benz # KABRIOLET # Lakier Oryginał# Zarej PL',
      'Sprzedam Opel Zafira',
      'Suzuki SX4 Lift # 4x4 # 1.6 Benzyna # Style # Nawigacja # Bezwypadkowy',
      'Hyundai I30 Hyundai i30 I CW 1.4 109KM 80kW 2009',
      'Audi A4B6 Kabriolet',
      'Bmw e60 525d 2007r lift automat',
      'Toyota Yaris 2012',
      'Volvo V50 1.6 D 2008 rok',
      'BMW Seria 5 Bmw e60 3.0 M pakiet Alu 18 Automat',
      'Citroën C3 Czujniki Parkowania, Aux,Hak',
      'Opel Combo 1,4i Klima, 5 osób, el. szyby, 166tys.km, 2006r.',
      'Bmw 730D 2009r full opcja mozliwa zamiana',
      'Duży Fiat 125. Posiadam także dawce.',
      'Audi A3 1.8Turbo LPG bez rdzy',
      'Fiat Doblo 1.3 2010',
      'Citroën C4 SpaceTourer Shine! Navi!Kamera!Pół Skóry!Bi Xenon!Full Opcja!Serwis ASO!Gwarancja!',
      'Ford Focus St MK2 2.5 Turbo',
      'BMW Seria 5 Xenon Navi Skóra Alu Idealna !!!',
      'Volkswagen Golf Hatchback • Salon Polska • Serwis ASO • Gwarancja • Dostępny od ręki',
      'SKODA Fabia 2002r. 1.2b 68hp ! Okazja! Wrocław Legnicka 62a',
      'Audi A6 Allroad A6 C5 2.7 biturbo 422km zakuty motor',
      'Peugeot 207 1.6 120KM # PANORAMA # CZUJNIKI # TEMPOMAT # Bezwypadkowy # Opłacony',
      'Mazda 3 Mazda 3 SkyPassion, pierwszy właściciel z polskiego salonu',
      'Mercedes-Benz Klasa A',
      'Fiat Stilo  1.9 JTD',
      'Mazda 5 skóra 2l Gaz nowa butla',
      'Opel Meriva 1.7 DTI',
      'Jeep Wrangler Sahara 2.0 PL',
      'Audi A6 Audi A6 C7 3.0 TDI Quatrro',
      'Renault Megane 1.6/130KM/Bose/Navi/Półskóra/Dwa komplety kół/Bezwypadkowa',
      'Volvo xc60 summum',
      'BMW F11 535D 313PS M-PAKIET BiXenon LED Panorama Skóra Navi 19 PIĘKNA',
      'Audi tt s-line super stan',
      'VW Passat b5 1.9 tdi 130KW 2002 rok 203 000km',
      'Nissan Sentra - unikat',
      'Sprzedam Volvo S60 2.4 D5',
      'Volkswagen Polo 1.4 benzyna.',
      'Audi a3 2.0 180 koni 18” gwint',
      'Opel Astra J 2012 Sports Tourer',
      'TOYOTA RAV4 Samochód dobrze utrzymany nadający się do eksploatacji.',
      'Mitsubishi lancer kombi',
      'Peugeot 208 Peugeot 208 1.6 eHdi 100KM',
      'Mercedes-Benz CLS Mercedes-Benz CLS LIFT pojemność 3500, 272 km BENZYNA',
      'Volkswagen Golf',
      'Ford Mondeo Kombi Mk3',
      'BMW Seria 3 BMW E46 1.8 Benzyna + LPG / OC 10 msc. / PT na rok',
      'Ford Mustang 5.0   421KM',
      'Opel Grandland X 2019r 36800km FV23% Biała Perła Navi Kamera Zarejestr',
      'Mercedes-Benz Vito 114 CDI',
      'Zastava yugo koral',
      'Peugeot RCZ Piękny 2010 1.6 156KM bezwypadkowy serwisowany!',
      'Audi A3 1.8 LPG // klimatyzacja // el. Szyby // hak // zamiana!',
      'Renault Scenic automat klima alu Warszawa Gwarancja 12 mies.',
      'Seat Leon Seat Leon 1.6 TDI 105KM, Panorama. Gorąco POLECAM!!!',
      'Mercedes-Benz ML ML 350 CDI, 1. Właściciel, 227 KM, Automat, Skóra, Navi, Xenon,',
      'Mitsubishi ASX Salon PL! 74tys przebieg! navi, 2017r rejestracja! Jak nowy!LIFT!',
      'Renault Laguna Renault Laguna II FL Kombii',
      'FIAT 125p 1500 oryginał',
      'Toyota Verso 1,6 z polskiego salonu',
      'Citroën C4 Picasso Nowy kompletny rozrząd bezwypadkowy gwarancja',
      'Kia Optima 2,4 203 KM,Automat Super stan',
      'Chevrolet Trax 1.4 Turbo AWD Mokka',
      'Skoda Octavia 1.6 TDI 105KM LIFT klimatyzacja automatyczna ŁADNY Gwarancja FILM',
      'MG Zr (Rover) 2004',
      'Audi a3 8p 2.0 TDI 2009r Lift! Led! Alu! Doinwestowana!',
      'Ford Mondeo kombi 2018 Trend X Gold',
      'Mitsubishi Eclipse Cross MITSUBISHI Eclipse Cross 1.5 T GPF Invite Plus CVT',
      'Volkswagen Golf Plus serwisowany w ASO .',
      'Opel Corsa Polski Salon po remoncie',
      'Fiat Doblo DOBLO cargo maxi F-vat',
      'SKODA Octavia 2004r 1.9 110hp ! Okazja! Wrocław Legnicka 62a',
      'Bmw e46 318i lpg',
      'Audi a6 2.0 tdi 140km Bre  Manual',
      'Fiat Bravo 1.4T 150KM Klimatronic Xenon USB Subwoofer Zarejestrowany',
      'Porsche Cayenne Porsche Cayenne 957 V6 3.6 karbon zadbany niemal ideał serwisowany ASO',
      'Audi A3 Audi A3 Sedan',
      'Seat Toledo Superwagen, 2008rok, 1.9TDi, Salon PL',
      'Audi A6 C5 2.8 1999 r',
      'Focus LIFT Kombi 1.8 TDCI 2009 rok bez DPF',
      'Mercedes-Benz CLS Japonia Idealny Zadbany Pełna Opcja 6.3 AMG',
      'Mitsubishi Space Gear Delica Space Gear 2.8TD 125KM Super Select 4x4 Blokada!',
      'Citroën C4 Grand Picasso Citroen C4 GrandPicasso 2016 przebieg 77500 - benzyna, manual.',
      'Renault Scenic Renault Scenic 2 dach panoramiczny',
      'Mercedes-Benz Klasa C Bugmaister AMG x 2, Czerwone skóry, Keiles , Perła ,Rolety , Full',
      'Audi A3 Audi A3',
      'BMW Seria 5 MPakiet 2.5i 192KM Skóra Xenon Navi Parktronic Tempomat Klimatronic',
      'BMW Seria 5 Sport 184KM Xenon Led Navi Webasto Skóra Zadbana !!!',
      'Volvo S80 Volvo S80 II 3.0 T6 PB+LPG AWD',
      'Seat Ibiza Po Opłatach,Serwisowany,Klimatyzacja,LIFT,Alufelgi',
      'Suzuki SX4 S-Cross 1.6 DDiS LIFT LED 4x4 Panorama Radar Keyles Automat Skóra Navi Kamera',
      'Nissan qashqai tekena rok 2017 lift automat ładny zamiana',
      'Mazda 6 Rocznik 2011',
      'Audi A6 Limousine Sport 40 TDI 204 KM quattro S tronic DEMO ASO Krotoski Łódź',
      'Audi RS7 4.0 TFSI 600 KM Dostępny OD RĘKI',
      'Ford Focus C-Max 1.6TDCi 90KM GHIA OD Emeryta',
      'Mazda 6 1.8 Benzyna Opłacony',
      'Sprzedam samochód',
      'Kia ceed 2009 2.0',
      'Audi S4 2013 AUDI S4 Premium',
      'Ford Mondeo 2.0 TDCi 130 Ps Titanium Convers Navi G.Fotele Serwis',
      'Suzuki Jimny 100% BEZWYPADKOWY *cały w oryginale*1 WŁAŚCICIEL* bez grama korozji',
      'Volvo XC 60 Volvo XC60 D5 AWD Summum 2014r.',
      'Skoda Octavia Skoda Octavia 1,6 TDI DSG sprzedaję z domu',
      'Honda Civic niezwykła Honda Civic Sport+ 180KM, 90 tys przebiegu, CAŁA W ORYGINALE',
      'Opel Corsa C 1.3 CDti *** 2006 rok ** 5 Drzwiowa',
      'Hyundai I30 1.4CRDi',
      'Mazda MX-5 Unikatowy kolor - Soul Red Crystal, 184 KM ! Wersja po liftingu',
      'Honda Jazz Honda Jazz 1.2 z 2007 klimatyzacja felgi aluminiowe',
      'Mercedes-Benz Klasa C Czarny z czerwonym wnętrzem',
      'SsangYong Korando Gwarancja 1 Rok Klimatronik Telefon Podgrzewane Fotele Super Stan',
      'Citroen c4 1.6 LPG BRC',
      'Bmw X3 E83 2.0d  bez dpf 4x4 Xdrive',
      'Ford Focus 1.5 TDCi Trend',
      'Opel Insignia 2.0 CDTI Sports Tourer',
      'Sprzedam Audi a6 c5 2.4 2001  quattro',
      'Fiat 126p  po odbudowie',
      'Renault Megane nawigacja tempomat bluetooth PDC hak',
      'Mercedes W221 S klasa long 350 CDI! Lift! Felgi Maybach!',
      'Opel Insignia Sprzedam Opla',
      'BMW Seria 3 BMW 318i touring',
      'Mercedes-Benz CLA Mercedes-Benz CLA 117 CUPE AMG LINE BEZwypadkowy',
      'BMW X6 BMW X6 35d',
      'Ford Kuga 2.0 TDCI 4x4*ORYGINAŁ 100%*TITANIUM*PANORAMA*Skóra*Nawigacja',
      'BMW Seria 3 Bmw 328 M pakiet LIFT 2010 sportowe wydech PRYWATNIE',
      'Opel astra 2 benzyna',
      'VW Golf 1.9 TDI !!!',
      'Peugeot 206 plus Zabezpieczony antykorozyjnie.',
      'Hyundai i40 1.7 128 tyś przebieg',
      'Audi RS4 Od ręki - 2.0 TFSI Quattro (450KM) | Układ wydechowy RS',
      'Nissan Juke Nissan Juke 1.2 Benzyna 2 kluczyki Bezwypadek Ledy Navi Kamery 360',
      'Skoda Octavia Salon Polska I Właściciel Serwisowany Pewne Auto FV23%',
      'Volvo V50 1.6 diesel',
      'Opel Insignia 1,5 turbo benzyna z gazem',
      'Sprzedam zamienie toyotę avensis',
      'Ford Focus Salon Polska 1.6 TDCI',
      'Toyota Auris 1.4 D4-D',
      'Seat Arona 95 KM Style Bezwypadkowa Full LED Nawigacja Podgrzewane Fotele FV23%',
      'Opel Insignia 2.0 CDTI 163 KM*BI XENON*LED*NAVI*Alu 19 OPC*bezwypadkowy*wzór*',
      'Renault Megane 1.7 Blue dCi, Salon Polska, Serwis ASO, Automat, Skóra, Navi,',
      'Kia Pro_cee\'d 1.6 CRDi, Skóra, Navi, Klimatronic, Tempomat, Parktronic',
      'Renault Scenic 1.2Turbo PółSkóry*Navi*Kamera Cof.*Bose*Klimatronic*Perfect Stan',
      'Kia Carens 1.7 CRDI 7 Osób Panorama Navi Kamera Led Tempomat',
      'Honda Accord VIII Skóra  Xenony Navi Szyber Możl. Zamiana Pl',
      'Opel Astra 2012 , diesel, start/stop, 191.500km',
      'Nissan Qashqai+2 1.6 cdi 4x4 kamera 360 ponorama 2013r',
      'Citroën C3 zadbany, faktura vat-marża, możliwa ZAMIANA !',
      'Renault Master RENAULT MASTER 9 os. 1 właściciel',
      '1.8 tdci 2008 rok klima sprawna długie oplaty polecam',
      'Audi 80 Cabrio * Zadbany Klasyk * Zamiana *',
      'Dacia Lodgy 12.2017*7os*Stepway*Navi*Klima*Esp*Kamera*Pdc*Temp*Komp*Gwar VGS !!!',
      'Toyota Corolla Verso 2.0 D4d klimatronik sprowadzony',
      'Kia Sportage 1,6 CRDI jak nowy !!! 22 tyś km',
      'Audi S4 2019 AUDI S4 Premium Plus',
      'Skoda Fabia **Ambition**salon PL**fak. 23%**benzyna**serwis**klima**Isofix**',
      'Ford S-Max Ford S-max Titanium S 11r 7-osób nawi felgi REWELACJA',
      'BMW Seria 1 F20 118D 143 KM Tempomat Parktroniki Oryginalny Przebieg Bezwypadkowy',
      'Sprzedam Hyundai Sonata',
      'Toyota Corolla Verso 2.0 D4d klimatronik sprowadzony',
      'Kia Sportage 1,6 CRDI jak nowy !!! 22 tyś km',
      'Audi S4 2019 AUDI S4 Premium Plus',
      'Skoda Fabia **Ambition**salon PL**fak. 23%**benzyna**serwis**klima**Isofix**',
      'Volvo V50 ekonomiczny*climatronic*pali jeździ**ICD**',
      'BMW Seria 3 2,0d 143ps 6-biegów * lift * climatronic * ICDauto',
      'Audi A3 1,8 benzyna 160 ps*kabriolet*skóra*xenon*led*ICDauto*',
      'Citroën C4 Picasso 1,6 hdi 110ps*climatronic dwustrefowy*ekonomiczny**ICD**',
      'Fiat Tipo 1.4 95KM POP (Salon PL, I właściciel, Bezwypadkowy, F-VAT 23%)',
      'MINI Cooper Cooper. Dostępny od ręki!!! 2022r.',
      'Toyota Yaris IDEALNY STAN bezwypadkowa salon PL przebieg tylko 28 tyś km jak NOWA',
      'CHRYSLER PT CRUISER 2.2 d , 2004 rok,',
      'Ford focus CC 2.0 136km',
      'Infiniti Fx35 AWD polift wersja sport  2006r',
      'Skoda Octavia 2.0TDI 2011r Lift *Alu felgi',
      'Honda Civic IX 2012 Bezwypadkowa Prywatnie',
      'Sprzedam Piękną Zadbaną Fieste 2013 r Salon Polska Prywatne Auto',
      'Dacia Duster 1.6 SCe, Salon Polska, 1. Właściciel, Serwis ASO, Navi, Klimatronic,',
      'Citroën C3 1.4 HDi, Klima, El. szyby',
      'Volvo S40 2,0d 2008 r. Lift Salon PL Bezwypadkowy 174 tys.km. VAT23%',
      'Volkswagen T-Roc 1.5 TSI 150KM czujniki, Bluetooth, Isofix, multifunkcja, Alu.',
      'Land Rover Range Rover Salon Polska Full Wersja Polecam',
      'Renault Clio Renault Clio II Storia 1.5 dci',
      'Ford Focus MK3 11R 1.6TDCI NAVI ORG 240tys klima, grzane siedzenia',
      'Zadbany Fiat FREEMONT 2012r 7 Osobowy Skóra !! Bezwypadkowy Opłacony',
      'Volkswagen Passat',
      'Opel Insignia 2.0Cdti 170KM Salon POLSKA Navi El. KLAPA',
      'Mercedes-Benz Clk 2.0 Kompressor 163km',
      'Fiat doblo 1.9 jtd osobowy',
      'Sprzedam audi a4  2.4v6',
      'Peugeot 206, benzyna, ważny przegląd i ubezpieczenie',
      'Volkswagen Passat 2.0 TDI 150km',
      'Mercedes-Benz Vito LONG, 8 osob, salonPL, I wlas, bezwypadkowy, idealny',
      'Ford Focus FOCUS 2.0 Benzyna 160 KM AUTOMAT Hatchback Pełna Faktura VAT',
      'BMW X3 E83 M57 3.0D xDrive 4x4 żeliwny silnik, wyposażona,automat',
      'Honda CR-V Diesel 2,2 Pierwszy właściciel',
      'Peugeot  5008 1.6 hdi Automat',
      'Ford Kuga 2.0TDCi_Z Niemiec_Piekna_Zadbana_Jak Nowa_REZERWACJA_',
      'Bmw 525d F11 Navi proff/Xenon/Panorama/Fotele Sport/Zadbana!',
      'Opel Meriva 1,4 90 ps Klima Super Stan',
      'Peugeot 308CC 1,6 benz, do poprawek, sprawny',
      'Opel Astra ASTRA 1,6 benzyna. Z polskiego salonu. 2 właściciel',
      'Volkswagen Passat Volkswagen Passat B6 Comfortline 2.0 TDI CR, 140 KM',
      'Renault Megane 2006',
      'BMW X3 Salon Polska Pakiet M pierwszy właściciel jak nowy',
      'BMW E90 320d 2.0 diesel',
      'Sprzedam Forda galaxy 1.9 2004 r',
      'Subaru OUTBACK 4x4 LPG okazjaa',
      'Ford Mondeo zadbany udokumentowany przebieg przygotowany do rejestracji',
      'Jeep Compass Od ręki - Upland 1.5 e-HYBRID 130KM |Pakiet Zimowy Upland|',
      'Renault Scenic 1.5 dci',
      'Ford Mondeo MK4 kombi',
      'Sprzedam Forda galaxy 1.9 2004 r',
      'Subaru OUTBACK 4x4 LPG okazjaa',
      'Ford Mondeo zadbany udokumentowany przebieg przygotowany do rejestracji',
      'Mazda 3 1.6 105KM#17 ALU#doposażona#opłaty#sprawdź',
      'Seat Leon Seat Leon 1.6, jeździ, dobry akumulator, ważny przegląd!',
      'Mercedes R-klasa w251 auto już w naprawie SPRAWNY',
      'Nissan//Juke//1.6 benzyna//tylko 61tys przebiegu//2016rok//',
      'Audi Q3 Advanced 35TFSI 150KM Manual 6-biegów 2022 Pakiet Comfort & Assistance',
      'Hyundai I40 dobrze wyposażony',
      'Volkswagen Passat Volkswagen Passat B5 1.9 TDI 130 KM',
      'Kia Ceed 1.6 GDI z LPG',
      'Renault Clio IV Lift Gaz LPG Ledy Salon PL VAT 23% Okazja GWARANCJA',
      'Sprzedam bmw x5 f15 3.0d pakiet Shadow Line',
      'Fiat Grande Punto',
      'Ładny//Ford//Grand//C-Max//książka serwisowa//7-osobowy//2012r',
      'Sprzedam Skoda Octavia',
      'Mercedes Benz C 220 Dlugie opłaty',
      'Peugeot 508 Serwis ASO Niski Przebieg',
      'Honda Civic 49tys Km. Lift',
      'Śliczna//BMW//745I//4.4LPG//Biznes Klas//Bogate Wyposazenie//',
      'Subaru Forester 2.0i(158KM)*Lift*Skóry*4x4*Klimatronik*I Wł.*Alu Felgi 16ASO Subaru',
      'Ford B-MAX Titanum Panorama Dach',
      'Ford Focus',
      'Audi Q5 3.0 TDI 240KM Quattro z DE Navi PDC Zarejestrowany w PL Gwarancja',
      'Skoda Octavia sprowadzona 25.08.2022 roku, przygotowana do rejestracji',
      'Vw Touran/7miejsc/HIGHLINE/Navi/Xenon/Piękny/WARTO!',
      'Volkswagen Golf R 4Motion',
      'Chevrolet Silverado 2021, 2.7L, porysowany lakier',
      'Audi A4 Avant 1.9 TDI',
      'Sprzedam audi a4 b6 1.8 T',
      'Citroen Berlingo 1.4 Benz/Gaz Klima Alufelgi',
      'Nissan qashqai 2.0 4x4',
      'Volkswagen Passat',
      'BMW E61 M-Pakiet Bi-Led 2006R',
      'Audi A1 1.6TDI CR*NAVI*Ledy*Klimatronic*Super STAN*z Niemiec*OPŁACONY*',
      'Volkswagen Golf',
      'vw golf VII kombi, fv 23%',
      'BMW E46 318 Gas/Benzinja',
      'Mercedes-Benz Vito Sprzedam pilnie - oferta ważna 2 dni.',
      'Skoda Octavia 1.6 TDI* Navi* Climatronic* Alu* PDC* Model 2013* Serwis* Gwarancja',
      'Chrysler Pacifica 2020 4x4 AWD LAUNCH EDITION Faktura Vat 23%',
      'Skoda Octavia 1.4 TSI 150KM FV23% czujniki, BT, alu, multifunkcja, Isofix, GPS',
      'Opel Corsa 1.4 Twinport 75KM czujniki, alu. BT, multifunkcja, Isofix, USB',
      'Opel Astra Alufelgi // Klima // El szyby // Po opłatach z Niemiec //',
      'Mitsubishi Lancer Evolution Mitsubishi Lancer EVO X 417KM 2008r.',
      'Audi A4 B5 1.6 BENZYNA',
      'AUDI A4 B7 2.0 TDI 140KM',
      'Skoda Superb Salon Polska, Wersja SPORTLINE 190KM Bezwypadkowy Gorąco Polecam',
      'Fiat Panda Fiat Panda',
      'MERCEDES W124 2.0 diesel',
      'Volvo V70 xenon, navi, automat, foteliki, skóra, 1 - właściciel',
      'Audi A3 8P  zarejestrowany',
      'Mercedes A 140 benzyna',
      'Sprzedam b.ładne zadbane a6lift 1,9tdi',
      'Audi a3 1.6 tdi DSG',
      'Renault Megane 1.6 16v*klima*alu*grzane fotele*4elszyby',
      'Toyota Sienna 2022, 2.5L, 4x4, od ubezpieczalni',
      'Lexus RX 2019, 3.5L, 4x4, porysowany lakier',
      'Chevrolet Tahoe 2022, 5.3L, 4x4, po gradobiciu',
      'Renault Clio 1.2 75KM klimatyzacja, odtwarzacz CD, Isofix, pólskóra',
      'Volkswagen caddy anglik po przekładce',
      'Mercedes-Benz Klasa E Serdecznie zapraszam Okazja..',
      'Mercedes-Benz Citan 109CDI Polski Salon',
      'Renault scenic II',
      'Mercedes Vito 2.2',
      'Ford S-Max FORD S-MAX 2.0 TDCI 2009',
      'Volkswagen Golf Plus 1.6 MPI 102 KM Skrzynia Automatyczna',
      'Ford Mondeo 2.0D 150 KM Automat Blisy Keyless Ledy Navi Alusy Opłacony Gwarancja',
      'Renault Scenic 1.6i GAZ LPG - Sprawny - Zamiana Raty Gwarancja',
      'Mercedes-Benz Klasa C C300 4 Matic/polski salon/od ręki/wynajem długoterminowy/',
      'BMW E90 LCI 320d',
      'Volkswagen Passat Passat b6 2.0 TDI BMP 140KM',
      'Renault Twingo 1.0 Sce 71 KM',
      'Volkswagen Golf VII 1.2TSI BMT Highline lounge',
      'Ford Explorer 3.5 v6 lpg 4x4 7osobowe',
      'Peugeot 3008 1.6 eHdi-Doinwestowany! AUTOMAT!Klimatronik!Zadbany',
      'Sprzedam Bmw x3 zamiana',
      'Peugeot 407 2.0 HDI ST Komfort EU4',
      'Hyundai i40 Hyundai i40',
      'Ford Kuga Bardzo dobry stan',
      'Renault Scenic Sprzedam Renault Grand Scenic 2',
      'Mazda 3 Mazda 3 16r 2.2 Diesel 150 KM, 1 właściciel, stan idealny, bogate wyp.',
      'Peugeot 3008 Sprzedam Peugeot 3008',
      'Ford Focus Mk2 2.0 oryginał Salon Polska',
      'Ford Mondeo MK4 2.0tdci Hatchback',
      'Sprzedam Volkswagen Golf 1.3',
      'Toyota Corolla Toyota Corolla 1.4 D 4D Premium Faktura VAT 23 % SALON PL',
      'Citroën C4 Grand Picasso Citroen Grand Picasso ! Sprowadzony ! Dobry egzemplarz !',
      'Mazda CX5 2.0B Europa Full Led Bogata Opcja Gwarancja Zarejestrowana',
      'Mercedes A160 benzyna+ gaz 2011',
      'Touareg V6 3.0 4×4TDI Automat skóra xsenon klimatronic',
      'Ford Focus Ford Focus 1.6 diesel 95km 2012',
      'Fiat Stilo1.9JTD okazja',
      'DAEWOO Matiz 0.8 niski przebieg dlugie opłaty bdb stan..',
      'Peugeot 308 1.2 PureTech Active Pack S&S',
      'Volvo XC 60 Oryg 100 tys km D4 190 Bezwypadkowy Śliczny',
      'Dodge Challenger Dodge Challenger SXT 3,6',
      'Auto pMercedes Vito',
      'Renault Clio , Salon Polska , Niski Przebieg , Super Stan',
      'Fiat Bravo Fiat Bravo 1.4 turbo benzyna sport xenon nawi klimatronik serwis',
      'Land Rover Discovery',
      'Megane Coupe 1.6 LPG',
      'Kia ceed panorama 1.6',
      'Tesla Model S S90D Salon Tesla',
      'Renault Scenic 2.0i 16V Benzyna Manual 6 biegów Klimatyzacja Alusy z Niemiec OPŁACONY',
      'Peugeot 508 Czarna Perła- dostojny, atrakcyjny, nadal nowoczesny - SALON POLSKA -',
      'Subaru Legacy 2005 r. 2,5 LPG 4x4 Salon PL',
      'Skoda Octavia Skoda Octavia 1.4 TSI Ambiente',
      'Subaru Legacy Subaru Legacy Kombi 2.0i +LPG, Polift, zadbany, doinwestowany',
      'Toyota Corolla 2.0 Hybrid Comfort',
      'Nissan Qashqai Stan idealny',
      'Audi A4 2.0 Benyzna 252KM !! 2017 !! 83 tys km !! Quattro !! Skora !!',
      'Mitsubishi Lancer Mitsubishi Lancer z polskiego salonu, bezwypadkowe, serwisowane.',
      'Bmw 116i Sport Line* 136KM*Xenon*Navi*Super Stan',
      'Peugeot 107 1.0 klima 2014r',
      'Toyota Avensis Combi 2.2 D-Cat 6-biegow ,webasto ,klimatronick.',
      'Śliczna ASTRA 1.6 *tylko 149.000 km *BOGATA OPCJA *Zero Rdzy *2007 ROK',
      'BMW E39 seria 5.',
      'Skoda Fabia 2012r**1.2 12V**Benzyna**Tylko 145tys km**Nowy Rozrząd**Bez Wkładu!!',
      'oldsmobile custom cruiser chevrolet caprice LS',
      'Audi S5 4.2 v8 POLSKI SALON!!!',
      'Skoda Octavia Skoda Octavia Laurin&Kllement 2.0 CR 140 km',
      'Volkswagen New Beetle 2.0 Benzyna Bezwypadkowy Oryginalny',
      'Chevrolet citation  do renowacji',
      'Honda CR-V CR-V 2.0 i-VTEC Manual Kamera PDC Serwis ASO-Lublin',
      'Toyota Corolla Disel',
      'Sprzedam Piękne BMW f11 525xd Po lift .Luxury',
      'Volkswagen Golf Volkswagen GOLF V 1.3 2005',
      'Hyundai ix20',
      'Lexus LS 600h F Sport 2013 Nowa Bateria Gwarancja',
      'Audi A6 Allroad Audi Allroad A6 C5 2,7 Quattro',
      'Ford Focus 2006 rok - uszkodzony.',
      'X3 F25 3.5D biturbo XDrive*313KM*Full Opcja*Serwis Aso*161tyś Przeb',
      'Golf 1,6 benz z Niemiec bezwypadek klima czarny 170 tys.km serwis',
      'Opel Astra Opel Astra EXECUTIVE Sedan',
      'Fiat Qubo 1.4 LPG Klimatyzacja',
      'Mercedes-Benz Klasa S Odsprzedam/odstąpię leasing Mercedes Benz S 400 D Long 2020',
      'Dacia Sandero Stepway Serwis do końca! Navi PDC Klima',
      'BMW Seria 3 BMW E46 coupe 2.0',
      'Toyota Aygo 1.0 VVT-I 72KM kamera, czujniki, USB, Isofix, multifunkcja, Alu.',
      'BMW X5 M Technik Individual V8 4.4 Biturbo FV 23%',
      'Opel Corsa 75 KM // Miejski 5 D ekonomiczny Możliwy zakup Na Raty //',
      'Volkswagen Golf sprzedam pieknego golfa 4 1.6 sr 5 drzwi przeb113 AUTOMAT',
      'Subaru impreza Sti N12',
      'Ford Mondeo 2,0 / 150 KM / Jak Nowy / NAVI / LED / Grzana Szyba / Salon PL / FV23%',
      'Opel Corsa 1.4 Benzyna * \'OPC\'* FULL BOGATA! Jak NOWA! * IDEAŁ!',
      'Honda Civic 2,0 / 158 KM / AUTOMAT / Benzyna / LED / KAMERA / Tempomat / Gwarancja',
      'Nissan Note Oryginał Automat Kamera Lane Assist Czujnik Martwego Pola Video Prezen',
      'MINI ONE 1.6 Ben 90KM # Klimatyzacja # Stan Idealny # Z Niemiec #',
      'Skoda Octavia 1.6 TDI 115KM alu, czujniki, BT, multifunkcja, Keyless Go, Isofix',
      'Nissan Qashqai 1.6I 117KM Klimatyzacja, czujniki, CD, Isofix, multifunkcja, Alu.',
      'Volvo V40 Rok: 2017, D3, R-DESING, Światła LED, Grzane Fotele, NAVI, GWARANCJA',
      'Opel Astra Czujniki, Salon PL, Nowe Klocki,150 Ps, Gwarancja, Serwis Olej. i Aso',
      'Isuzu D-Max Pierwszy właściciel, oryginalny przebieg, bezwypadkowy, Isuzu D-Max',
      'Jeep grand cheroke limited edition',
      'Ford Mustang 2.3 EcoBoost 290 KM Lift 2018 Cyfrowe Zegary',
      'Toyota RAV 4  96r.',
      'Chrysler Town & Country 2012r, 3,6 LPG',
      'Opel Insignia 2.0 BiTurbo Salon PL',
      'BMW Seria 1 BMW 1, Pełny M Pakiet, Rewelacyjny Stan',
      'OKAZJA ! PIĘKNY Opel Corsa C 2005r. 1.3 CDTI Klimatronik, Sprowadzony',
      'BMW Seria 5 BMW 525 d, M pakiet zew/wew., panorama, zaw. sportowe M, automat',
      'Ford Mondeo 2.0 TDCi 150 KM Manual Led Kamera Key Less Go El Kla Gwarancja',
      'Toyota Auris Toyota Auris 2 salon Polska 1.6 benzyna pierwsza rejestracja 2019',
      'Skoda Citigo Skoda Citigo, benzyna 1.0, rok produkcji 2014',
      'Skoda Fabia 1.4 *Wspomaganie*Super stan*Dwa Kpl opon*Serwisowany*Opłat',
      'Audi a4 2.4 V6 kombi skóra xenon opłacony ze Szwajcarii ZADBANY',
      'Kia soul 1.6GDI automat 57tys km',
      'Renault clio IV salon Polska',
      'Volkswagen Golf samochodzik antykryzysowy :) fv VAT',
      'Chevrolet Spark Chevrolet Spark Bogate Wyposażenie ,Mały Przebieg !!!',
      'Skoda fabia 1,4 bezyna',
      'Opel Corsa pierwsza rejestracja 2009, stan dobry, niskie spalanie, klimatyzacja*',
      'OPEL CORSA 1.2 turbo EDITION S&S 2020R',
      'Ford Mondeo Mk4 1.8tdci Ghia X',
      'VW Transporter T3 Kamper ,MULTIVAN',
      'VW Touran 2.0tdi 2.0 tdi 170 DSG Highline Navi Android DSP Ładny',
      'Cadillac Seville #4.6#300KM#Bogate wyposażenie#Klasyk#Gwarancja',
      'Sprzedam Ford Mondeo mk4',
      'Dacia sandero II 1.2b_klimatyzacja_navi_alumy_tempomat_ bluetooth',
      'Mercedes W203 C200, 2,2 CDI, 116 KM',
      'Renault Laguna 2.0i~140ps~KlimaTronik~Bezwypadkowa~Serwisowana~Bardzo Zadbana~TOP',
      'Subaru OUTBACK #2.5#156KM#4WD#Bogate wyposażenie#Gwarancja',
      'Opel Meriva 1,4 LPG 2009 r. Lift Salon PL',
      'Ford Mondeo 1 właściciel z Niemiec bezwypadek serwisowany',
      'VW Caddy Life 1.9 TDI 105km BLS 2006r',
      'Jeep Grand Cherokee',
      'Audi TT Audi TT Coupe 1.8T Quattro Warszawa',
      'Skoda Octavia 4#4+NAVI PLUS+2.0 150PS+Bezwypadek+El.Klapa',
      'Jeep Grand Cherokee Jeep Grand Cherokee IV',
      'Citroën C3 Citroen C3 III 1,2 PureTech 2019 rok 20850 km',
      'Toyota RAV4 2,2 d4d 136 ps 4x4*climatronic*pdc**ICD**',
      'Ford Tourneo Custom Sport',
      'Sprzedam BMW X5 M 313 km',
      'Sprzedam Fiat punto',
      'Renault Laguna 2,0 dci 150 ps automat*nawigacja*pali jeździ**ICD**',
      'Audi Q5 pierwszy wlasciciel, cesja leasingu stan idealny',
      'Opel Astra 1.4TurboBenz Doinwestowana',
      'Audi A6',
      'Kia Venga 1.4 benzyna! 46 tyś przebieg! Solar dach! Niemcy! Unikat!',
      'Mercedes-Benz GLE GLE 300d 4MATIC - wkrótce w salonie',
      'Toyota Avensis 76. Toyota Avensis 1.6 D-4D Active',
      'Toyota Yaris Hybrid Aut. 100KM FV23% kamera, czujniki, USB, multifunkcja, Isofix',
      'Audi a3 8l  2001 r. 1.8t LPG Quattro',
      'Renault Megane Renault Megane IV 1.6 Sce Grandcoupe - 2017r',
      'Ford Mustang 3.7 V6',
      'Chevrolet Captiva Chevrolet Captiva 2.2',
      'Hyundai Tucson 2.0Benzynka_Super Stan_Zadbany_Z Niemiec _Ful Opcja_Doinwestiwany',
      'Audi a3 8l  2001 r. 1.8t LPG Quattro',
      'Renault Megane Renault Megane IV 1.6 Sce Grandcoupe - 2017r',
      'Opel Vectra C 1.8',
      'Mercedes-Benz Klasa C 2.2cdi , 2008r ,manual 6-biegów ,',
      'Mercedes-Benz Klasa C 2,0 Hybryda Nawigacja Kamera',
      'Peugeot Bipper',
      'Toyota Celica Turbo GT4',
      'Sprzedam Opla Insignia',
      'Nissan Micra NAVI+Panorama+Klimatronik+Keyless GO+Jedyna Taka',
      'Renault Scenic 2 1.6 16V benzyna+ gaz',
      'Mitsubishi Asx 2011 1.6 benzyna',
      'SprzedamToyota Yaris 1.3 automat',
      'Skoda Octavia 2009',
      'Volkswagen Fox * 2010 Rok * 1.4 Tdi * Niemcy !!',
      'Subaru Forester Pierwszy właściciel, garażowany w domu jednorodzinnym, serwisowany w A',
      'Suzuki SX4 S-Cross 1.6 DDiS 120KM czujniki, kamera, alu, multifunkcja, BT, GPS, Isofix',
      'Skoda Octavia 1.6 TDI 116KM czujniki, Isofix, BT, alu. multifunkcja, Eco Start Stop',
      'Opel Corsa C 2006 benzyna plus gaz',
      'Ford Edge 2.0 TDI 210KM Full Opcja Ładny europa',
      'Ford Mustang Mustang GT V8, Gwarancja, Pierwszy Właściciel, Salon, Max. Wyposażenie',
      'Opel Astra 1.7 CDTI. 110KM. Navi. Gwarancja !!!',
      'Fiat 500 Fiat 500 automat + LPG z USA',
      'Opel Zafira',
      'Ford Focus * Salon PL * 1-WŁ * Serwis ASO * Bezwypadkowy * 1,6TDCI * 95KM *',
      'BMW X5 M50d Individual / Ceramika',
      'Nissan Micra mały przebieg technicznie jak nowy SALON POLSKA!',
      'Peugeot 508 Nowy Silnik 27tys km 2018R Serwis ASO Nowe Opony',
      'Suzuki SX4 S-Cross 1.6 BENZYNA 120KM BIAŁA PERŁA * klimatyzacja * radio *',
      'Audi SQ5 3.0TFSI 354KM Q LED Panorama ACC Virtual Audi Wrocław STAŁA RATA',
      'Seat Leon',
      'Ford Focus Full LED Klimatronik Blis Alusy17 Navigacja Chromy Gwarancja Opłacony',
      'Fiat Stilo Fiat Stilo 1.6 LPG Kombi szyberdach świetny stan FAKTURA VAT',
      'Jeep Patriot 2.0 Diesel 140km 4x4 HAK bardzo zadbany i wyposażony zrobiony rozrząd',
      'Audi SQ5 Audi SQ5',
      'Porsche Panamera 4,8 400 ps*skóra*xenon*mały przebieg*silnik pali*full**ICD**',
      'Peugeot 308 1,6 benzynka 156 ps*climatronic*pdc*tempomat*ICDauto*',
      'Ford Fiesta mk7 lift 1.25 benzyna klimatyzacja 2017r bezwypadkowy',
      'Audi A6 Tylko 151Tyś Skóra Grzane Foele Xenon Ledy Navi Parktronik Tył',
      'Dacia Duster SALON POLSKA 1,6i 4x4 navi klima kamera cofania podgrzewane fotele',
      'Peugeot 508 1.2 PureTech GT S&S EAT8',
      'Toyota Aygo 1.0 VVT-i X-play Salon Polska Gwarancja 12m-cy',
      'Ford Fiesta Fort Fiesta 1,4 benzyna+lpg 2008',
      'Audi A4 B6 1.9 TDI 130km 2003',
      'Kia Ceed 1.6 DIESEL 115KM * klima * el.szyby * radio * zadbany',
      'Jaguar F-Pace Jaguar F-Pace 2.0 i4D',
      'Mercedes-Benz Klasa E bezwypadek z Niemiec serwisowany avangarde',
      'Cadillac Modell: Eldorado Biarrity 4.5 V8 1989 rok sprowadzony',
      'Audi a4 b8 2.0 TDI',
      'Opel Meriva Sprowadzona z Niemiec opłacona automat',

    ],
    age: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
    vip: [false, false, false, false, false, false, true],
    countryOfOrigin: [
      'Polska',
      'Niemcy',
      'USA',
      'Francja',
      'Szwajcaria',
      'Włochy',
      'Wielka Brytania',
      'Austria',
      'Szwecja',
    ],
    mileage: [
      '100 000',
      '110 000',
      '120 000',
      '130 000',
      '140 000',
      '150 000',
      '160 000',
      '170 000',
    ],
    img: [
      'https://ireland.apollo.olxcdn.com:443/v1/files/vi7qvu2z9ick1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/z0kezraii4o8-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/v426nxsfik5t2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/lcht3vugmh352-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/jxwdh0ycswm31-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/grqer3j27hzf3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/gw8wzkdmdhkj3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/tzpmnce2nzne2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/dl91gt4mklim2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/7s9rtiidj1j11-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/cag1l21qs4mh1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/zuijc2zir5cd-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/92u7a5bct6ek-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/lzo4kcvytjy81-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/2fvcsavpckhv2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/axs1bqf5qnbb3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/ppifqqwe7u63-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/4n4q3dv3v62o2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/6846mdl9a1oq2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/lj0ug1hc87kd-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/a6c0nqvb8524-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/dlnj6hc1i4kn2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/57h9cfwfl9pp-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/d0ye3dkxijgm-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/j7q34ojw4ft82-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/1pddlv4zxba4-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/alxkjtb6pkak1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/31d8fbtbhyik-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/j31nuvv7w7uv2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/3zihwwc5kz083-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/1duwhdtiwb5k3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/5r1h62dnvkz3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/r8dxkvu62yky1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/r31ffw58q8ty1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/ccee6jzw613e3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/2v520i251ill1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/mitrxualemln-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/dn9k798n4r4m3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/y3mk71hbsj743-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/2xvzadj34b3q3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/39cz0nwuz2fo-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/n1xnrj3s2hur1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/z64phjqu3bk93-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/d58zqnzyo7cc3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/yhkmnnlulytr3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/xp1ojiu33jq8-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/sv3sey42ixkm1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/brugbqn0hpkb-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/edbj3mkoifx71-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/sl44g2o4da5v2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/kdv3wb5mr65g2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/yzuu5izcnkyr2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/ehs64sn9t1yl3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/yvtddo67jyji-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/5iihlkf6j50w1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/sn01fftav1s-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/93cnfq79kfv7-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/vq81cirsbb2y1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/gl4f5r2b6fia-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/6wtfp2slixrw-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/3kjm3rwjvhb61-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/2apn8qyb12tk1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/znagp1j7pole2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/ucbneo5dckbo1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/z9j6woib48y42-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/f2b37eos93l22-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/dmxrnfh4sq051-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/axq6m8ap1z2f3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/mwdi172fvg2o3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/p7ci5gi8yl1h2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/dcj0txugizjh1-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/y6djo0am6qc83-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/kd1585kb0g2v3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/dqy7q0k3k0372-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/wtqfupgn1a7p3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/aivmoneb4lwk2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/q0ew3i0xxur61-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/n63k9ktzivlm2-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/4osqi7xlfjwu3-PL/image;s=2000x0;q=50',
      'https://ireland.apollo.olxcdn.com:443/v1/files/pd8lx7sqmu943-PL/image;s=2000x0;q=50',
    ],
    verified: [true, false],
    city: [
      'Augustów',
      'Bartoszyce',
      'Bełchatów',
      'Będzin',
      'Biała Podlaska',
      'Białobrzegi',
      'Białogard',
      'Białystok',
      'Biecz',
      'Bielsk Podlaski',
      'Bielsko-Biała',
      'Bieruń',
      'Bochnia',
      'Bolesławiec',
      'Brodnica',
      'Brzeg',
      'Brzesko',
      'Busko-Zdrój',
      'Bydgoszcz',
      'Bytom',
      'Chełm',
      'Chełmek',
      'Chojnice',
      'Chorzów',
      'Ciechanów',
      'Ciechocinek',
      'Cieszyn',
      'Czaplinek',
      'Czarnków',
      'Czechowice-Dziedzice',
      'Czeladź',
      'Częstochowa',
      'Człuchów',
      'Dąbrowa Górnicza',
      'Dębica',
      'Dęblin',
      'Działdowo',
      'Działoszyce',
      'Dzierżoniów',
      'Elbląg',
      'Ełk',
      'Gdańsk',
      'Gdynia',
      'Giżycko',
      'Gliwice',
      'Głogów',
      'Gniezno',
      'Gorlice',
      'Gorzów Wielkopolski',
      'Gostyń',
      'Grodzisk Mazowiecki',
      'Grójec',
      'Grudziądz',
      'Hrubieszów',
      'Iława',
      'Imielin',
      'Inowrocław',
      'Jarocin',
      'Jarosław',
      'Jasło',
      'Jastrzębie-Zdrój',
      'Jaworzno',
      'Jelenia Góra',
      'Józefów',
      'Kalisz',
      'Kamienna Góra',
      'Kamień Pomorski',
      'Karpacz',
      'Kartuzy',
      'Katowice',
      'Kąty Wrocławskie',
      'Kędzierzyn-Koźle',
      'Kępno',
      'Kętrzyn',
      'Kielce',
      'Kłodzko',
      'Koło',
      'Kołobrzeg',
      'Konin',
      'Końskie',
      'Koszalin',
      'Kościan',
      'Kościerzyna',
      'Kozienice',
      'Koźmin Wielkopolski',
      'Kórnik',
      'Kraków',
      'Kraśnik',
      'Krosno',
      'Krotoszyn',
      'Krzanowice',
      'Kutno',
      'Kwidzyn',
      'Legionowo',
      'Legnica',
      'Leszno',
      'Leżajsk',
      'Lębork',
      'Libiąż',
      'Lidzbark Warmiński',
      'Limanowa',
      'Lipno',
      'Lubań',
      'Lubin',
      'Lublin',
      'Lubliniec',
      'Łańcut',
      'Łapy',
      'Łęczyca',
      'Łomianki',
      'Łomża',
      'Łódź',
      'Łuków',
      'Malbork',
      'Mielec',
      'Międzyrzecz',
      'Międzyzdroje',
      'Mikołajki',
      'Mikołów',
      'Milicz',
      'Mińsk Mazowiecki',
      'Mława',
      'Morąg',
      'Mosina',
      'Mrągowo',
      'Mszana Dolna',
      'Mszczonów',
      'Mysłowice',
      'Myślenice',
      'Namysłów',
      'Nowa Sól',
      'Nowe Miasto Lubawskie',
      'Nowy Dwór Mazowiecki',
      'Nowy Sącz',
      'Nowy Targ',
      'Nowy Tomyśl',
      'Nysa',
      'Oborniki',
      'Oborniki Śląskie',
      'Olecko',
      'Oleśnica',
      'Olkusz',
      'Olsztyn',
      'Oława',
      'Opole',
      'Ostrołęka',
      'Ostrowiec Świętokrzyski',
      'Ostróda',
      'Ostrów Mazowiecka',
      'Ostrów Wielkopolski',
      'Ostrzeszów',
      'Oświęcim',
      'Otwock',
      'Pabianice',
      'Piaseczno',
      'Piła',
      'Piotrków Trybunalski',
      'Pisz',
      'Pleszew',
      'Płock',
      'Płońsk',
      'Pniewy',
      'Polkowice',
      'Poznań',
      'Pruszcz Gdański',
      'Pruszków',
      'Przemyśl',
      'Pszczyna',
      'Puławy',
      'Pułtusk',
      'Racibórz',
      'Radlin',
      'Radom',
      'Radomsko',
      'Radzymin',
      'Rawa Mazowiecka',
      'Reda',
      'Ruda Śląska',
      'Rumia',
      'Rybnik',
      'Rzepin',
      'Rzeszów',
      'Sandomierz',
      'Sanok',
      'Serock',
      'Sędziszów',
      'Siedlce',
      'Siemianowice Śląskie',
      'Sieradz',
      'Skarżysko-Kamienna',
      'Skierniewice',
      'Słubice',
      'Słupca',
      'Słupsk',
      'Sopot',
      'Sosnowiec',
      'Stalowa Wola',
      'Starachowice',
      'Stargard',
      'Starogard Gdański',
      'Strzegom',
      'Sucha Beskidzka',
      'Sulechów',
      'Sulejów',
      'Suwałki',
      'Szamotuły',
      'Szczecin',
      'Szczecinek',
      'Szczyrk',
      'Szczytno',
      'Środa Wielkopolska',
      'Świdnica',
      'Świebodzice',
      'Świebodzin',
      'Świecie',
      'Świętochłowice',
      'Świnoujście',
      'Tarczyn',
      'Tarnowskie Góry',
      'Tarnów',
      'Tczew',
      'Tomaszów Mazowiecki',
      'Toruń',
      'Tychy',
      'Ustka',
      'Ustroń',
      'Wadowice',
      'Wałbrzych',
      'Wałcz',
      'Warszawa',
      'Wągrowiec',
      'Wejherowo',
      'Węgorzewo',
      'Węgrów',
      'Wieluń',
      'Wisła',
      'Władysławowo',
      'Włocławek',
      'Wodzisław Śląski',
      'Wolsztyn',
      'Wołomin',
      'Wrocław',
      'Września',
      'Wyszków',
      'Zabrze',
      'Zakopane',
      'Zambrów',
      'Zamość',
      'Zawiercie',
      'Ząbki',
      'Zduńska Wola',
      'Zgierz',
      'Zgorzelec',
      'Zielona Góra',
      'Złotów',
      'Żagań',
      'Żary',
      'Żory',
      'Żyrardów',
    ],
  },
];

export default CarData;
